config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
  root 'home#index'
  get '/theloai/:id' => 'theloais#show' ,as: :theloai
  get '/truyen/:id' => 'truyens#show'   ,as: :truyen
  get '/new' =>'new#show'
  get '/all' => 'truyens#all'
  get '/signup'  => 'users#new'
  resources :users
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/uptruyen' =>'edittruyens#new'
  
  post 'truyens' =>'edittruyens#create'
  get '/themtheloai' =>'theloais#new'
  resources :theloais
  get '/edit' =>'edittruyens#list'
  get '/admin' =>'admin#show'
  get '/super' =>'admin#super'
  patch '/truyen/:id' => 'edittruyens#update'
  resources :truyen
  get 'edittruyen/:id/' =>'edittruyens#edit' ,as: :edittruyen
  resources :binhluan
  post '/binhluans' => 'binhluans#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
  belongs_to :truyen, optional: true
end

app/models/theloai.rb
class Theloai < ApplicationRecord
  has_many :truyens
end

app/models/truyen.rb
class Truyen < ApplicationRecord
    belongs_to :theloai
    has_many :binhluans
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def show
  end
  def super
    @users=User.all
    @binhluans=Binhluan.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @theloais=Theloai.all
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def show
  @theloais=Theloai.all
  @truyens=Truyen.order("updated_at DESC")
end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/binhluans_helper.rb
module BinhluansHelper
end

app/helpers/edittruyens_helper.rb
module EdittruyensHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theloais_helper.rb
module TheloaisHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/uptheloai_helper.rb
module UptheloaiHelper
end

app/helpers/uptruyen_helper.rb
module UptruyenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/show.html.erb
<ul>
  <li>
    <a href="<%=themtheloai_path%>"  class="btn btn-default">cập nhật thêm thể loại<a>
    </li>
    <li>
      <a href="<%=edit_path%>"  class="btn btn-default">Chỉnh Sửa Truyện<a>
      </li>
      <li>
        <a href="<%=uptruyen_path%>"  class="btn btn-default">up thêm truyện<a>
        </li>
        <li>
          <a href="<%=signup_path%>"  class="btn btn-default">dang ky<a>
          </li>
          <li>
            <a href="<%=login_path%>"  class="btn btn-default">dang nhap<a>
            </li>
            <li>
              <a href="<%=home_path%>"  class="btn btn-default">về trang chủ<a>
              </li>
            </ul>

app/views/admin/super.html.erb
<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <ul>
              <% @users.each do |t|%>
              <li>
                <%= t.first_name%><%= t.last_name%><%= t.email%>
              </li>
              <%end%>
            </ul>
          </div>
          <div class="col-md-6">
            <ul>
              <% @binhluans.each do |t|%>
              <li>
                <%= t.content%><%= t.truyen_id%><%= t.user_id%>
              </li>
              <%end%>
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FAM-Truyện Song Ngữ</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>