config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home' => 'home#index'
  root 'home#index'
  get '/theloai/:id' => 'theloais#show' ,as: :theloai
  get '/truyen/:id' => 'truyens#show'   ,as: :truyen
  get '/new' =>'new#show'
  get '/all' => 'truyens#all'
  get '/signup'  => 'users#new'
  resources :users
  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/uptruyen' =>'edittruyens#new'
  
  post 'truyens' =>'edittruyens#create'
  get '/themtheloai' =>'theloais#new'
  resources :theloais
  get '/edit' =>'edittruyens#list'
  get '/admin' =>'admin#show'
  get '/super' =>'admin#super'
  patch '/truyen/:id' => 'edittruyens#update'
  resources :truyen
  get 'edittruyen/:id/' =>'edittruyens#edit' ,as: :edittruyen
  resources :binhluan
  post '/binhluans' => 'binhluans#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/binhluan.rb
class Binhluan < ApplicationRecord
  belongs_to :truyen, optional: true
end

app/models/theloai.rb
class Theloai < ApplicationRecord
  has_many :truyens
end

app/models/truyen.rb
class Truyen < ApplicationRecord
    belongs_to :theloai
    has_many :binhluans
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def show
  end
  def super
    @users=User.all
    @binhluans=Binhluan.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @theloais=Theloai.all
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def show
  @theloais=Theloai.all
  @truyens=Truyen.order("updated_at DESC")
end
end

app/controllers/theloais_controller.rb
class TheloaisController < ApplicationController
  def show
    @theloais=Theloai.all
    @theloai = Theloai.find(params[:id])
    @truyens = @theloai.truyens
  end
  def new
    @theloai = Theloai.new
    @theloais=Theloai.all
  end
  def create
    @theloai = Theloai.new(theloai_params)
    if @theloai.save
      redirect_to '/themtheloai'
    end
  end
  private
  def theloai_params
    params.require(:theloai).permit(:title)
  end
end

app/controllers/truyens_controller.rb
class TruyensController < ApplicationController
  def show
    @theloais=Theloai.all
    @truyen = Truyen.find(params[:id])
    @binhluans=@truyen.binhluans.order("updated_at DESC")
    @binhluan = Binhluan.new
  end
  def all
    @theloais=Theloai.all
    @truyens=Truyen.order("name_vn ASC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/binhluans_helper.rb
module BinhluansHelper
end

app/helpers/edittruyens_helper.rb
module EdittruyensHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/theloais_helper.rb
module TheloaisHelper
end

app/helpers/truyens_helper.rb
module TruyensHelper
end

app/helpers/uptheloai_helper.rb
module UptheloaiHelper
end

app/helpers/uptruyen_helper.rb
module UptruyenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/theloais/new.html.erb
<h1>Thêm thể loại</h1>
<h3>các thể loại hiện có</h3>
<ol>
  <% @theloais.each do |t|%>
  <li>
    <%=t.title %>
  </li>
  <%end%>
</ol>
<%= form_for(@theloai) do |f| %>
<div class="col-sm-8">
  <p>
    <%= f.label :title  %><br>
    <%= f.text_field :title ,class: "form-control"%>
  </p>
  <%= f.submit "Thêm",class: "btn btn-default" %>
</div>
<%end%>
<a href="<%=uptruyen_path%>" class="btn btn-default">up thêm truyện<a>
  <a href="<%=home_path%>" class="btn btn-default">về trang chủ<a>

app/views/theloais/show.html.erb
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
  rel="stylesheet" type="text/css">
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-97841360-1', 'auto');
  ga('send', 'pageview');

</script>
</head>

<body>
  <body>
    <div class="navbar navbar-default navbar-fixed-top navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><span>Brand</span></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-ex-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active">
              <a href="<%= home_path %>">Trang Chủ<i class="fa fa-border fa-home pull-left"></i></a>
            </li>
            <li>
              <a href="<%= new_path %>">Truyện Mới Cập Nhật</a>
            </li>
            <li>
              <a href="<%= all_path %>">Tất Cả Các Truyện</a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-expanded="false">Thể Loại<br><i class="fa fa-caret-down pull-right"></i></a>
              <ul class="dropdown-menu" role="menu">
                <% @theloais.each do |t|%>
                <li>
                  <a href="<%= theloai_path(t) %>"><%= t.title%></a>
                </li>
                <%end%>
              </ul>
            </div>
          </div>
        </div>
        <div class="navbar navbar-default navbar-fixed-top navbar-inverse">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse" id="navbar-ex-collapse">
              <ul class="nav navbar-left navbar-nav">
                <li class="active">
                  <a href="<%= home_path %>">Trang Chủ<i class="fa fa-border fa-home pull-left"></i></a>
                </li>
                <li>
                  <a href="<%= new_path %>">Truyện Mới Cập Nhật</a>
                </li>
                <li>
                  <a href="<%= all_path %>">Tất Cả Các Truyện</a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                  aria-expanded="false">Thể Loại<br><i class="fa fa-caret-down pull-right"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <% @theloais.each do |t|%>
                    <li>
                      <a href="<%= theloai_path(t) %>"><%= t.title%></a>
                    </li>
                    <%end%>
                  </ul>
                </li>
                <% if current_user %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                  aria-expanded="false"><%= current_user.email %><br><i class="fa fa-caret-down pull-right"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="<%= logout_path%>">log out</a>"</li>
                  </ul>
                </li>
              </ul>
              <% else %>
            </ul>
            <% end %>
          </ul>
          <form class="navbar-form navbar-right text-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Tìm Truyện</button>
          </form>
          <p class="navbar-right navbar-text">Truyện Song &nbsp;Ngữ
            <br>
          </p>
          <% if current_user %>
          <% else %>
          <a class="btn btn-default navbar-btn navbar-left" data-toggle="modal" href="<%=login_path%>"><i class="fa fa-star fa-fw"></i>Đăng Nhập</a>
          <%end%>
        </div>
      </div>
    </div>
    <div class="section">
      
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <h1 class="text-left">
              <i class="fa fa-star fa-fw"></i>
              <b>
                <i>Truyện Song Ngữ Anh-Việt</i>
              </b>
            </h1>
          </div>
          <div class="row">
            <div class="col-md-12">
              <hr>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2><%= @theloai.title%></h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <hr>
          </div>
        </div>
      </div>
      <div class="section">
        <div class="container">
          <% @truyens.each do |t|%>
          <div class="section">
            <div class="container">
              <div class="row">
                <div class="col-md-4">
                  <a href="<%= truyen_path(t)%>" style="opacity: 1;"><img src="<%= t.image%>" class="img-responsive"></a>
                </div>
                <div class="col-md-6">
                  <h1>
                    <a href="<%=truyen_path(t)%>"><%= t.name_vn%></a></h1>
                    <h3><%= t.name_en%></h3>
                  </div>
                  <div class="col-md-2">
                    <p class="text-center">Thời diểm cập nhật:
                      <br><%= t.updated_at%></p>
                      <a href="<%=truyen_path(t)%>" class="btn btn-default">Đọc truyện này<a>
                      </div>
                    </div>
                  </div>
                </div>
                <%end%>
              </div>
            </div>
            <div class="container">
              <div class="row">
                <div class="col-md-12">
                  <hr>
                </div>
              </div>
            </div>
</div>


          </body>
          </html>